# Generated by Django 6.0.6 on 2026-07-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_grid_layout', models.CharField(choices=[('2x2', '2x2 Grid (4 items)'), ('1x2', '1x2 Grid (2 items side-by-side)')], default='2x2', help_text='Choose the mobile category slider layout.', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
