# Generated by Django 6.0.6 on 2026-07-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_banners_on_desktop',
            field=models.BooleanField(default=False, help_text='Show hero banners on PC and large screens (lg viewport and up).'),
        ),
    ]
