# Generated by Django 6.0.6 on 2026-07-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_show_banners_on_desktop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_banners_on_desktop',
        ),
    ]
