# Generated by Django 6.0.6 on 2026-07-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_show_banners_on_desktop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_text',
            field=models.TextField(blank=True, help_text='Physical address shown in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_text_en',
            field=models.TextField(blank=True, help_text='Physical address shown in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_text_hy',
            field=models.TextField(blank=True, help_text='Physical address shown in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_text_ru',
            field=models.TextField(blank=True, help_text='Physical address shown in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_download_url',
            field=models.URLField(blank=True, help_text='e.g. http://ma1.am'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_qr_code',
            field=models.ImageField(blank=True, help_text='QR Code for desktop footer', null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_en',
            field=models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_hy',
            field=models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ru',
            field=models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_fb',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.CreateModel(
            name='FooterCompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_hy', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(help_text='URL or relative path like /about/', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Company Link',
                'verbose_name_plural': 'Company Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_hy', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(help_text='URL or relative path like /catalog/', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Product Link',
                'verbose_name_plural': 'Product Links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
