# Generated by Django 6.0.6 on 2026-07-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_address_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_vk',
            field=models.URLField(blank=True, verbose_name='VKontakte URL'),
        ),
        migrations.DeleteModel(
            name='FooterProductLink',
        ),
    ]
