# Generated by Django 6.0.6 on 2026-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_social_vk_delete_footerproductlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_news_layout',
            field=models.CharField(choices=[('GRID', 'Grid'), ('SLIDER', 'Carousel Slider')], default='GRID', help_text='Choose how favourite posts are displayed on the homepage.', max_length=10),
        ),
    ]
