# Generated by Django 6.0.6 on 2026-07-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_featured_news_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(blank=True, max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('address_text', models.TextField(blank=True, help_text='Physical address shown in footer')),
                ('address_text_hy', models.TextField(blank=True, help_text='Physical address shown in footer', null=True)),
                ('address_text_ru', models.TextField(blank=True, help_text='Physical address shown in footer', null=True)),
                ('address_text_en', models.TextField(blank=True, help_text='Physical address shown in footer', null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('social_fb', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('social_vk', models.URLField(blank=True, verbose_name='VKontakte URL')),
                ('social_instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('social_linkedin', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('social_tiktok', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('social_youtube', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('app_download_url', models.URLField(blank=True, help_text='e.g. http://ma1.am')),
                ('app_qr_code', models.ImageField(blank=True, help_text='QR Code for desktop footer', null=True, upload_to='footer/')),
                ('copyright_text', models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255)),
                ('copyright_text_hy', models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255, null=True)),
                ('copyright_text_ru', models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255, null=True)),
                ('copyright_text_en', models.CharField(blank=True, default='© 2026 Martin Star. All rights reserved.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_text_hy',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_text_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='app_download_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='app_qr_code',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text_hy',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_fb',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_tiktok',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_vk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_youtube',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_news_layout',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='footercompanylink',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='core.footersettings'),
        ),
    ]
