# Generated by Django 6.0.6 on 2026-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_footersettings_remove_sitesettings_address_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('title', models.CharField(help_text='Short milestone title (e.g., Canned goods production start)', max_length=255)),
                ('title_hy', models.CharField(help_text='Short milestone title (e.g., Canned goods production start)', max_length=255, null=True)),
                ('title_ru', models.CharField(help_text='Short milestone title (e.g., Canned goods production start)', max_length=255, null=True)),
                ('title_en', models.CharField(help_text='Short milestone title (e.g., Canned goods production start)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional longer description')),
                ('description_hy', models.TextField(blank=True, help_text='Optional longer description', null=True)),
                ('description_ru', models.TextField(blank=True, help_text='Optional longer description', null=True)),
                ('description_en', models.TextField(blank=True, help_text='Optional longer description', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/history/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company Milestone',
                'verbose_name_plural': 'Company Milestones',
                'ordering': ['year'],
            },
        ),
    ]
