# Generated by Django 6.0.6 on 2026-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны (например: Россия)', max_length=100)),
                ('map_code', models.CharField(help_text='Код страны для карты (ISO 3166-1 alpha-2, например: RU, US, AM)', max_length=5)),
                ('region', models.CharField(choices=[('Australia', 'Australia & Oceania'), ('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Europe', 'Europe')], default='Europe', max_length=50)),
                ('cities', models.TextField(blank=True, help_text='Города присутствия (через запятую). Оставьте пустым, если не нужно.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Export Country',
                'verbose_name_plural': 'Export Countries',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(help_text='Partner logo (transparent PNG/SVG recommended)', upload_to='partners/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'verbose_name_plural': 'Partner Logos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
