# Generated by Django 6.0.6 on 2026-07-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exportcountry_partnerlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportcountry',
            name='cities',
        ),
    ]
