# Generated by Django 6.0.6 on 2026-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_exportcountry_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logistics_layout',
            field=models.CharField(choices=[('SPLIT', 'Modern Split Grid'), ('CARD', 'Floating Card Over Banner')], default='SPLIT', help_text='Toggle the visual style of the Logistics section on the partnership page.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_news_layout',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
