# Generated by Django 6.0.6 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_logistics_layout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Yandex Map Latitude (e.g., 40.1872)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Yandex Map Longitude (e.g., 44.5152)', max_digits=9)),
                ('is_headquarters', models.BooleanField(default=False, help_text='Pin this as the main HQ at the top of the page')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Branch Office',
                'verbose_name_plural': 'Branch Offices',
                'ordering': ['-is_headquarters', 'order'],
            },
        ),
    ]
