# Generated by Django 6.0.6 on 2026-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_branchoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(help_text='Full vacancy description. Use HTML or linebreaks.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hr_cc_emails',
            field=models.CharField(blank=True, help_text='Comma-separated list of CC emails (e.g., marketing@martinstar.am, ceo@martinstar.am).', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hr_email',
            field=models.EmailField(default='hr@martinstar.am', help_text='Main email for receiving job applications.', max_length=254),
        ),
    ]
