# Generated by Django 6.0.6 on 2026-07-09 13:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vacancy_sitesettings_hr_cc_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(help_text='Full vacancy description.'),
        ),
    ]
