# Generated by Django 6.0.6 on 2026-07-09 13:27

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Full vacancy description using blocks.', null=True),
        ),
    ]
