# Generated by Django 6.0.6 on 2026-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vacancy_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnerLogo',
            new_name='Partner',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='partner',
            name='show_on_online_store',
            field=models.BooleanField(default=False, verbose_name='Show in Buy Online'),
        ),
        migrations.AddField(
            model_name='partner',
            name='show_on_partners_page',
            field=models.BooleanField(default=True, verbose_name='Show on Partners Page'),
        ),
        migrations.AddField(
            model_name='partner',
            name='online_store_link',
            field=models.URLField(blank=True, null=True, verbose_name='Buy Online Link'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_page_link',
            field=models.URLField(blank=True, null=True, verbose_name='Partner Official Page Link'),
        ),
    ]
