# Generated by Django 6.0.6 on 2026-07-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic_alter_post_created_at_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_favourite',
            field=models.BooleanField(default=False, help_text='Pin this post to the homepage'),
        ),
    ]
