# Generated by Django 6.0.6 on 2026-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutritional_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutritional_value_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutritional_value_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutritional_value_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='box_dimensions',
            field=models.CharField(blank=True, help_text='e.g., 285 x 315 x 235 mm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='box_dimensions_en',
            field=models.CharField(blank=True, help_text='e.g., 285 x 315 x 235 mm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='box_dimensions_hy',
            field=models.CharField(blank=True, help_text='e.g., 285 x 315 x 235 mm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='box_dimensions_ru',
            field=models.CharField(blank=True, help_text='e.g., 285 x 315 x 235 mm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.CharField(blank=True, help_text='e.g., 579/2424 kcal/kJ', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='in grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='in grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_storage_temp',
            field=models.IntegerField(blank=True, help_text='in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_storage_temp',
            field=models.IntegerField(blank=True, help_text='in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_options',
            field=models.CharField(blank=True, help_text='e.g., 100 g / 50 pcs', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_options_en',
            field=models.CharField(blank=True, help_text='e.g., 100 g / 50 pcs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_options_hy',
            field=models.CharField(blank=True, help_text='e.g., 100 g / 50 pcs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_options_ru',
            field=models.CharField(blank=True, help_text='e.g., 100 g / 50 pcs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='in grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_period_days',
            field=models.IntegerField(blank=True, help_text='Storage period in days', null=True),
        ),
    ]
