# Generated by Django 6.0.6 on 2026-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_nutritional_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_dimensions_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='box_dimensions_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='box_dimensions_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing_options_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing_options_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing_options_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='box_dimensions_unit',
            field=models.CharField(choices=[('mm', 'mm'), ('cm', 'cm')], default='mm', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_options_unit',
            field=models.CharField(choices=[('g/pcs', 'g / pcs'), ('kg/pcs', 'kg / pcs'), ('ml/pcs', 'ml / pcs'), ('l/pcs', 'l / pcs'), ('pcs', 'pcs')], default='g/pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_dimensions',
            field=models.CharField(blank=True, help_text='e.g., 285x315x235', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_options',
            field=models.CharField(blank=True, help_text='e.g., 100/50', max_length=100),
        ),
    ]
