# Generated by Django 6.0.6 on 2026-07-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_box_dimensions_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='box_dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='box_dimensions_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing_options_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Main cover photo for the product.', upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in grams', max_digits=10)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('box_dimensions', models.CharField(blank=True, help_text='e.g., 285x315x235', max_length=100)),
                ('box_dimensions_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm')], default='mm', max_length=10)),
                ('packing_options', models.CharField(blank=True, help_text='e.g., 100/50', max_length=100)),
                ('packing_options_unit', models.CharField(choices=[('g/pcs', 'g / pcs'), ('kg/pcs', 'kg / pcs'), ('ml/pcs', 'ml / pcs'), ('l/pcs', 'l / pcs'), ('pcs', 'pcs')], default='g/pcs', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Specific photo for this variant. Leave blank to use main product photo.', null=True, upload_to='products/options/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
                'ordering': ['weight'],
            },
        ),
    ]
