# Generated by Django 6.0.6 on 2026-07-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.brand'),
        ),
    ]
