# Generated by Django 6.0.6 on 2026-07-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal title for admin panel', max_length=255)),
                ('hero_banner_desktop', models.ImageField(help_text='Wide format for desktop screens', upload_to='banners/')),
                ('hero_banner_mobile', models.ImageField(help_text='Compact/vertical format for mobile screens', upload_to='banners/')),
                ('banner_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-id'],
            },
        ),
    ]
