# Generated by Django 6.0.6 on 2026-07-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='packing_options',
            field=models.CharField(blank=True, help_text='Enter quantity in box (e.g., 50). System will auto-prepend weight (e.g., 100g/50pcs).', max_length=100),
        ),
    ]
