# Generated by Django 6.0.6 on 2026-07-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productoption_packing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='packing_options_unit',
        ),
    ]
