# Generated by Django 6.0.6 on 2026-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_productoption_packing_options_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='box_dimensions',
            field=models.CharField(blank=True, help_text='L x W x H (e.g., 285x315x235)', max_length=100),
        ),
    ]
