# Generated by Django 6.0.6 on 2026-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_productoption_box_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='hero_banner_desktop',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='hero_banner_mobile',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_en',
            field=models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_hy',
            field=models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='banners/'),
        ),
    ]
