# Generated by Django 6.0.6 on 2026-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_herobanner_hero_banner_desktop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='banner_link',
        ),
    ]
