# Generated by Django 6.0.6 on 2026-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_herobanner_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='show_on_desktop',
            field=models.BooleanField(default=False, help_text='Show this banner on PC/large screens'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='show_on_mobile',
            field=models.BooleanField(default=True, help_text='Show this banner on mobile devices'),
        ),
    ]
