# Generated by Django 6.0.6 on 2026-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_herobanner_show_on_desktop_herobanner_show_on_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='banner_link',
            field=models.URLField(blank=True, help_text='Optional link when clicking the banner'),
        ),
    ]
