# Generated by Django 6.0.6 on 2026-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_herobanner_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='placement',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('BLOG_LIST', 'Blog List Page'), ('BLOG_POST', 'Blog Post Inner Page'), ('PARTNERS', 'Partners Page'), ('PRODUCTS', 'Products List Page'), ('ABOUT', 'About Us Page'), ('CAREERS', 'Careers Page'), ('CONTACT', 'Contact Page')], default='HOME', help_text='Where this banner should be displayed', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated banners. Overrides image if provided.', null=True, upload_to='banners/videos/'),
        ),
    ]
