# Generated by Django 6.0.6 on 2026-07-07 10:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_herobanner_placement_herobanner_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical)', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_mobile_en',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical)', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_mobile_hy',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical)', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_mobile_ru',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical)', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='show_text_overlay',
            field=models.BooleanField(default=True, help_text='Показывать заголовок и подзаголовок поверх баннера'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст подзаголовка под главным заголовком'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст подзаголовка под главным заголовком', null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_hy',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст подзаголовка под главным заголовком', null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='subtitle_ru',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст подзаголовка под главным заголовком', null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст заголовка (можно форматировать)', null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_hy',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст заголовка (можно форматировать)', null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_ru',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст заголовка (можно форматировать)', null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_en',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Desktop banners. Overrides image.', null=True, upload_to='banners/videos/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_hy',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Desktop banners. Overrides image.', null=True, upload_to='banners/videos/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_mobile',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Mobile banners. Overrides mobile image.', null=True, upload_to='banners/videos/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_mobile_en',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Mobile banners. Overrides mobile image.', null=True, upload_to='banners/videos/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_mobile_hy',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Mobile banners. Overrides mobile image.', null=True, upload_to='banners/videos/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_mobile_ru',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Mobile banners. Overrides mobile image.', null=True, upload_to='banners/videos/mobile/'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video_file_ru',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Desktop banners. Overrides image.', null=True, upload_to='banners/videos/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Desktop Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_en',
            field=models.ImageField(blank=True, help_text='Desktop Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_hy',
            field=models.ImageField(blank=True, help_text='Desktop Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Desktop Banner image', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст заголовка (можно форматировать)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm for animated Desktop banners. Overrides image.', null=True, upload_to='banners/videos/'),
        ),
    ]
