# Generated by Django 6.0.6 on 2026-07-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_herobanner_image_mobile_herobanner_image_mobile_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(help_text='Partner logo (transparent PNG/SVG recommended)', upload_to='partners/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'verbose_name_plural': 'Partner Logos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Desktop Banner image. Рекомендуемый размер: 1920x300 пикселей.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_en',
            field=models.ImageField(blank=True, help_text='Desktop Banner image. Рекомендуемый размер: 1920x300 пикселей.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_hy',
            field=models.ImageField(blank=True, help_text='Desktop Banner image. Рекомендуемый размер: 1920x300 пикселей.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical). Рекомендуемый размер: 1080x1920 пикселей.', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_mobile_en',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical). Рекомендуемый размер: 1080x1920 пикселей.', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_mobile_hy',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical). Рекомендуемый размер: 1080x1920 пикселей.', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_mobile_ru',
            field=models.ImageField(blank=True, help_text='Mobile Banner image (Vertical). Рекомендуемый размер: 1080x1920 пикселей.', null=True, upload_to='banners/mobile/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image_ru',
            field=models.ImageField(blank=True, help_text='Desktop Banner image. Рекомендуемый размер: 1920x300 пикселей.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='placement',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('BLOG_LIST', 'Blog List Page'), ('BLOG_POST', 'Blog Post Inner Page'), ('PARTNERS', 'Partners Page'), ('PARTNERSHIP', 'Partnership (B2B) Page'), ('PRODUCTS', 'Products List Page'), ('ABOUT', 'About Us Page'), ('CAREERS', 'Careers Page'), ('CONTACT', 'Contact Page')], default='HOME', help_text='Where this banner should be displayed', max_length=50),
        ),
    ]
